<?php

declare(strict_types=1);

/*
 * This file is part of the "schema_health" extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 */

namespace Brotkrueml\SchemaHealth\Model\Type;

use Brotkrueml\Schema\Core\Model\AbstractType;

/**
 * Fitness-related activity designed for a specific health-related purpose, including defined exercise routines as well as activity prescribed by a clinician.
 */
final class ExercisePlan extends AbstractType
{
    protected static $propertyNames = [
        'about',
        'accessMode',
        'accessModeSufficient',
        'accessibilityAPI',
        'accessibilityControl',
        'accessibilityFeature',
        'accessibilityHazard',
        'accessibilitySummary',
        'accountablePerson',
        'activityDuration',
        'activityFrequency',
        'additionalType',
        'additionalVariable',
        'aggregateRating',
        'alternateName',
        'alternativeHeadline',
        'associatedAnatomy',
        'associatedMedia',
        'audience',
        'audio',
        'author',
        'award',
        'category',
        'character',
        'citation',
        'code',
        'comment',
        'commentCount',
        'contentLocation',
        'contentRating',
        'contributor',
        'copyrightHolder',
        'copyrightYear',
        'countryOfOrigin',
        'creator',
        'dateCreated',
        'dateModified',
        'datePublished',
        'description',
        'disambiguatingDescription',
        'discussionUrl',
        'editor',
        'educationalAlignment',
        'educationalUse',
        'encoding',
        'encodingFormat',
        'epidemiology',
        'exampleOfWork',
        'exerciseType',
        'expires',
        'funder',
        'genre',
        'guideline',
        'hasPart',
        'headline',
        'identifier',
        'image',
        'inLanguage',
        'intensity',
        'interactionStatistic',
        'interactivityType',
        'isAccessibleForFree',
        'isBasedOn',
        'isFamilyFriendly',
        'isPartOf',
        'keywords',
        'learningResourceType',
        'legalStatus',
        'license',
        'locationCreated',
        'mainEntity',
        'mainEntityOfPage',
        'material',
        'medicineSystem',
        'mentions',
        'name',
        'offers',
        'pathophysiology',
        'position',
        'potentialAction',
        'producer',
        'publication',
        'publisher',
        'publishingPrinciples',
        'recognizingAuthority',
        'recordedAt',
        'releasedEvent',
        'relevantSpecialty',
        'repetitions',
        'restPeriods',
        'review',
        'sameAs',
        'schemaVersion',
        'sourceOrganization',
        'spatial',
        'spatialCoverage',
        'sponsor',
        'study',
        'subjectOf',
        'temporal',
        'temporalCoverage',
        'text',
        'thumbnail',
        'thumbnailUrl',
        'timeRequired',
        'translator',
        'typicalAgeRange',
        'url',
        'version',
        'video',
        'workExample',
        'workload',
    ];
}
