services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\SchemaHealth\:
    resource: '../Classes/*'

  Brotkrueml\SchemaHealth\EventListener\RegisterAdditionalProperties:
    tags:
      - name: event.listener
        identifier: 'ext-schema-health/registerAdditionalProperties'
