services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\SchemaHealth\:
    resource: '../Classes/*'

  Brotkrueml\SchemaHealth\EventListener\RegisterAdditionalProperties:
    tags:
      - name: event.listener
        identifier: 'ext-schema-health/registerAdditionalProperties'
        event: Brotkrueml\Schema\Event\RegisterAdditionalTypePropertiesEvent

  Brotkrueml\SchemaHealth\EventListener\RegisterTypePropertiesMovedFromCoreToPending:
    tags:
      - name: event.listener
        identifier: 'ext-schema-health/registerTypePropertiesMovedFromCoreToPending'
        event: Brotkrueml\Schema\Event\RegisterAdditionalTypePropertiesEvent
